# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logsumexp <- function(x) {
    .Call('_rates_logsumexp', PACKAGE = 'rates', x)
}

bjR1 <- function(betajk_j, sdjk2_j, zkl, tau2) {
    .Call('_rates_bjR1', PACKAGE = 'rates', betajk_j, sdjk2_j, zkl, tau2)
}

bjR0 <- function(betajk_j, sdjk2_j, alpha, lambda) {
    .Call('_rates_bjR0', PACKAGE = 'rates', betajk_j, sdjk2_j, alpha, lambda)
}

deltis <- function(betajk_j, sdjk2_j, lambda, alpha) {
    .Call('_rates_deltis', PACKAGE = 'rates', betajk_j, sdjk2_j, lambda, alpha)
}

