// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "rates_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// logsumexp
double logsumexp(NumericVector x);
RcppExport SEXP _rates_logsumexp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logsumexp(x));
    return rcpp_result_gen;
END_RCPP
}
// bjR1
double bjR1(VectorXd betajk_j, VectorXd sdjk2_j, MatrixXd zkl, VectorXd tau2);
RcppExport SEXP _rates_bjR1(SEXP betajk_jSEXP, SEXP sdjk2_jSEXP, SEXP zklSEXP, SEXP tau2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< VectorXd >::type betajk_j(betajk_jSEXP);
    Rcpp::traits::input_parameter< VectorXd >::type sdjk2_j(sdjk2_jSEXP);
    Rcpp::traits::input_parameter< MatrixXd >::type zkl(zklSEXP);
    Rcpp::traits::input_parameter< VectorXd >::type tau2(tau2SEXP);
    rcpp_result_gen = Rcpp::wrap(bjR1(betajk_j, sdjk2_j, zkl, tau2));
    return rcpp_result_gen;
END_RCPP
}
// bjR0
double bjR0(NumericVector betajk_j, NumericVector sdjk2_j, double alpha, double lambda);
RcppExport SEXP _rates_bjR0(SEXP betajk_jSEXP, SEXP sdjk2_jSEXP, SEXP alphaSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type betajk_j(betajk_jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sdjk2_j(sdjk2_jSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(bjR0(betajk_j, sdjk2_j, alpha, lambda));
    return rcpp_result_gen;
END_RCPP
}
// deltis
NumericVector deltis(NumericVector betajk_j, NumericVector sdjk2_j, double lambda, double alpha);
RcppExport SEXP _rates_deltis(SEXP betajk_jSEXP, SEXP sdjk2_jSEXP, SEXP lambdaSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type betajk_j(betajk_jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sdjk2_j(sdjk2_jSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(deltis(betajk_j, sdjk2_j, lambda, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rates_logsumexp", (DL_FUNC) &_rates_logsumexp, 1},
    {"_rates_bjR1", (DL_FUNC) &_rates_bjR1, 4},
    {"_rates_bjR0", (DL_FUNC) &_rates_bjR0, 4},
    {"_rates_deltis", (DL_FUNC) &_rates_deltis, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_rates(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
